### ISSUE TITLE
Invalid API description for unbound functions

### ISSUE THREAD

**Issue by t-bonk** [cap-js/openapi#55]
Hello,

in my CAP Java based service, I have defined the following CDS model:

db/db-model.cds:
```cds
entity TestEntity {
    key ID: String;
    name: String;
}
```

srv/test-service.cds:
```cds
using { TestEntity } from '../db/db-model';

service TestService {
  entity TestServiceEntity as projection on TestEntity;

  define type DataEntry {
    ID: String;
    name: String;
  }

  function getEntries(id: String not null, name: String not null) returns array of DataEntry;
}
```

When generating the openapi.json using this command:

```bash
cds compile srv/test-service.cds -2 openapi --openapi:url /odata/v4/TestService > openapi.json
```

I can see that the [generated API description](https://github.com/user-attachments/files/17801783/openapi.json) for the unbound function doesn't result in a conformant OData v4 URL. When using Swagger UI the following request URL is generated which is invalid:

```
http://localhost:8080/odata/v4/TestService/getEntries?id=%27k1%27&name=%27v1%27
```

The valid OData v4 request URL looks like this:

```
http://localhost:8080/odata/v4/TestService/getEntries(id=%27k1%27,name=%27v1%27)
```

This are the versions that are used in my project:

| swaggerui-cds          | <Add your repository here>                                                                         |
| ---------------------- | -------------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                              |
| @cap-js/openapi        | 1.0.5                                                                                              |
| @sap/cds               | 8.2.3                                                                                              |
| @sap/cds-compiler      | 5.2.0                                                                                              |
| @sap/cds-dk            | 8.2.3                                                                                              |
| @sap/cds-fiori         | 1.2.7                                                                                              |
| @sap/cds-foss          | 5.0.1                                                                                              |
| @sap/cds-mtxs          | 2.1.0                                                                                              |
| @sap/eslint-plugin-cds | 3.0.5                                                                                              |
| CAP Java SDK           | 3.3.1                                                                                              |
| Java                   | 21.0.5, home: /Library/Java/JavaVirtualMachines/sapmachine-21.jdk/Contents/Home                    |
| Maven                  | 3.9.9, home: /Users/D021624/SAPDevelop/Tools/apache-maven-3.9.9                                    |
| Node.js                | v20.17.0                                                                                           |
| OS                     | Mac OS X, 15.1, arch: aarch64                                                                      |
| Spring Boot            | 3.3.5                                                                                              |
| cds4j                  | 3.3.1                                                                                              |
| home                   | /Users/D021624/SAPDevelop/CAPJava/Samples/swaggerui/node_modules/@sap/cds-dk/node_modules/@sap/cds |

Can you please fix this issue?

Best regards
Thomas

**Comment by t-bonk** [comment]
Hello @RoshniNaveenaS,

are there any updates regarding this issue? Since it is related to an incident of an external customer, it is quite urgent.

Tanks & Best regards
Thomas

**Comment by RoshniNaveenaS** [comment]
> Hello @RoshniNaveenaS,
> 
> are there any updates regarding this issue? Since it is related to an incident of an external customer, it is quite urgent.
> 
> Tanks & Best regards Thomas

Hello @t-bonk ,
I will look into this on priority and get back to you

**Comment by RoshniNaveenaS** [comment]
Hello @t-bonk,
Could you let us know what is the expected output URL from openAPI side?
@ralfhandl do you think we have to make any changes to the URLgeneration in this case?

**Comment by t-bonk** [comment]
Hello @RoshniNaveenaS,

in my opinion the metadata for a function should like this:

```yaml
"/getEntries(id={id},name={name})": {
      "get": {
        "summary": "Invokes function getEntries",
        "tags": [
          "Service Operations"
        ],
        "parameters": [
          {
            "required": true,
            "in": "path",
            "name": "id",
            "description": "String value needs to be enclosed in single quotes",
            "schema": {
              "type": "string",
              "pattern": "^'([^']|'')*'$"
            }
          },
          {
            "required": true,
            "in": "path",
            "name": "name",
            "description": "String value needs to be enclosed in single quotes",
            "schema": {
              "type": "string",
              "pattern": "^'([^']|'')*'$"
            }
          }
        ],
```

for an unbound function defined in CDS like this:

```cds
function getEntries(id: String not null, name: String not null) returns array of DataEntry;
```

The URI for an OData V4 function call looks like this:

`.../getEntries(id='k1',name='n1')`

Best regards
Thomas
